[0m00:28:42.340434 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D7A722BE00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D7A4F81D10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D7A842FC50>]}


============================== 00:28:42.344565 | 70ab4fb6-869b-4f9d-9b99-44dc304e087f ==============================
[0m00:28:42.344565 [info ] [MainThread]: Running with dbt=1.10.9
[0m00:28:42.345073 [debug] [MainThread]: running dbt with arguments {'partial_parse': 'True', 'profiles_dir': 'C:\\Users\\NIKHIL\\.dbt', 'send_anonymous_usage_stats': 'True', 'warn_error': 'None', 'cache_selected_only': 'False', 'target_path': 'None', 'version_check': 'True', 'invocation_command': 'dbt init financedb', 'log_format': 'default', 'use_colors': 'True', 'introspect': 'True', 'debug': 'False', 'log_cache_events': 'False', 'fail_fast': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'use_experimental_parser': 'False', 'printer_width': '80', 'indirect_selection': 'eager', 'log_path': 'logs', 'write_json': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'static_parser': 'True'}
[0m00:28:42.359193 [debug] [MainThread]: Starter project path: D:\Nikhil\Projects\DBT\dbt_snowflake\financedb\venv\Lib\site-packages\dbt\include\starter_project
[0m00:28:42.370315 [info ] [MainThread]: 
Your new dbt project "financedb" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m00:28:42.370952 [info ] [MainThread]: Setting up your profile.
[0m00:33:43.996273 [info ] [MainThread]: Profile financedb written to C:\Users\NIKHIL\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m00:33:43.998969 [debug] [MainThread]: Command `dbt init` succeeded at 00:33:43.998649 after 301.78 seconds
[0m00:33:43.999691 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D7AA3FE8B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D7A9ABFBF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D7AA415E10>]}
[0m00:33:44.000424 [debug] [MainThread]: Flushing usage events
[0m00:33:45.457711 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m01:46:55.441281 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000016CD032BE00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000016CCE081D10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000016CD153BC50>]}


============================== 01:46:55.450630 | 870d8dfe-e269-4263-8131-29056c70066c ==============================
[0m01:46:55.450630 [info ] [MainThread]: Running with dbt=1.10.9
[0m01:46:55.452381 [debug] [MainThread]: running dbt with arguments {'partial_parse': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True', 'use_colors': 'True', 'cache_selected_only': 'False', 'target_path': 'None', 'warn_error': 'None', 'invocation_command': 'dbt run', 'log_format': 'default', 'version_check': 'True', 'introspect': 'True', 'debug': 'False', 'printer_width': '80', 'fail_fast': 'False', 'no_print': 'None', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'log_cache_events': 'False', 'log_path': 'logs', 'indirect_selection': 'eager', 'write_json': 'True', 'static_parser': 'True', 'profiles_dir': 'C:\\Users\\NIKHIL\\.dbt'}
[0m01:46:55.453293 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path D:\Nikhil\Projects\DBT\dbt_snowflake\financedb\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m01:46:55.454641 [debug] [MainThread]: Command `dbt run` failed at 01:46:55.454446 after 0.29 seconds
[0m01:46:55.455136 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000016CD15AC180>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000016CD1417AD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000016CD13D19D0>]}
[0m01:46:55.455671 [debug] [MainThread]: Flushing usage events
[0m01:46:57.119551 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m21:23:20.438824 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BFE262BE00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BFE0375D10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BFE3837C50>]}


============================== 21:23:20.491898 | 4e363a65-2def-451b-a644-ff8350a7d22c ==============================
[0m21:23:20.491898 [info ] [MainThread]: Running with dbt=1.10.9
[0m21:23:20.493459 [debug] [MainThread]: running dbt with arguments {'partial_parse': 'True', 'profiles_dir': 'C:\\Users\\NIKHIL\\.dbt', 'send_anonymous_usage_stats': 'True', 'use_colors': 'True', 'cache_selected_only': 'False', 'target_path': 'None', 'warn_error': 'None', 'invocation_command': 'dbt run', 'log_format': 'default', 'version_check': 'True', 'introspect': 'True', 'debug': 'False', 'printer_width': '80', 'fail_fast': 'False', 'no_print': 'None', 'use_experimental_parser': 'False', 'quiet': 'False', 'empty': 'False', 'log_cache_events': 'False', 'indirect_selection': 'eager', 'log_path': 'logs', 'write_json': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'static_parser': 'True'}
[0m21:23:20.494722 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path D:\Nikhil\Projects\DBT\dbt_snowflake\financedb\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m21:23:20.496625 [debug] [MainThread]: Command `dbt run` failed at 21:23:20.496376 after 0.56 seconds
[0m21:23:20.497410 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BFE38AC180>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BFE3717AD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BFE36D19D0>]}
[0m21:23:20.498074 [debug] [MainThread]: Flushing usage events
[0m21:23:22.669030 [debug] [MainThread]: An error was encountered while trying to flush usage events
